### ISSUE TITLE
Unknown property 'hystrix.command'

### ISSUE THREAD

**Issue by rama292087** [KoalaTea/castaway#9]
hystrix command is not recognized in .property or .yml file, can you please guide me on resolving this issue.

![image](https://user-images.githubusercontent.com/66622503/84026654-53e15700-a9ab-11ea-8a8f-a0dfdce3e0b2.png)

**Comment by KoalaTea** [comment]
Are you sure this is the right repo? I do not know what hystrix is or where it is relevant to this repo.
